# platform :ios, '9.0'

target 'WebRTCHandsOn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! # <- コメントアウト解除

  # Pods for WebRTCHandsOn
  ##### 追記ここから #####
  pod 'WebRTC', '58.17.16937'
  pod 'Starscream', '~> 2.0.3'
  pod 'SwiftyJSON'
  ##### 追記ここまで #####
end

